# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.controller_default:
        class: AppBundle\Controller\DefaultController
        autowire: true

    app.controller_secured:
        class: AppBundle\Controller\SecuredController
        autowire: true
        calls:
            - [ setAuthenticationUtils, [ '@security.authentication_utils' ] ]
